### ISSUE TITLE
Homebridge

### ISSUE THREAD

**Issue by ctaylora1231** [juliuscc/heos-api#1]
Any way this could be turned into a homebridge plugin to control heos speakers from a iOS device. I’m a newb so please excuse my ignorance....

**Comment by juliuscc** [comment]
Yes it should be possible to use this package in that package. This package is a wrapper for all possible api-calls.

Basically this package makes it easier to talk to any heos-device.

I would love to help if you have any more questions or need help getting started. I have not had any use cases to test this package on so I'm not really sure how good / bad it is, but if anything doesn't work I'll gladly fix it.

**Comment by ctaylora1231** [comment]
Awesome. I would love your help getting it started. Kinda new to all of this. I already have Homebridge installed on my home computer. I have a couple plug-ins already installed and working properly.  I just don’t know what steps need to been done to make this compatible with the homepage server.

**Comment by juliuscc** [comment]
First of all you will have to write your own plugin. This project will not be a plugin only for homebridge as it is a general purpose tool, however use this project to simplify all the api-calls. To create a plugin for homebridge check out [this link](https://github.com/nfarina/homebridge#plugin-development) for information on how to do that.

I have not made any plugins for homebridge so I can not help you with that. Please tell me if you stumble on any problems with heos-api and I'll gladly help with them.

**Comment by ctaylora1231** [comment]
Thank you
