### ISSUE TITLE
Large responses lead to JSON parse error

### ISSUE THREAD

**Issue by RobertMe** [juliuscc/heos-api#10]
Currently any TCP packet received on the socket (```connection.on('data', ...```) is immediately parsed, as it's assumed it's a complete message. But this isn't necessarily the case. For example the response to ```browse/search``` might be too large to fit in a single TCP packet. This then leads to a JSON parse error in ```dataHandler.js``` line 64.

According to the HEOS CLI docs every message will end on a newline. So I believe a better (but not complete) solution is to keep a buffer of the received message(s) and only run the data event handler when the buffer ends on ```}\r\n``` (so the closing bracked followed by a newline).
Although this solution isn't complete as it might still lead to issues when:
1. Multiple messages are received in one TCP packet for which the last message is too long (which will hold all messages). Although I'm not sure if multiple messages can/will be send in one TCP packet
2. The contents of a message contains ```}\r\n```

**Comment by juliuscc** [comment]
Could it be viable to count the ```{``` and only run the data event handler when there are enough ```}``` ?

I really do not know how to solve multiple packages though.

**Comment by juliuscc** [comment]
This month is really busy for me so if you would like to create a pull request that would be very much appreciated. Otherwise I will try to solve this.

**Comment by RobertMe** [comment]
I don't believe counting the number of `{` and `}`s will be safe. This as there might be some odd cases where either of those could be in a string (say an album/artist/song name). Checking if the packet ends on `}\r\n` would be safer I think. As such a sequence will be much less likely.

**Comment by juliuscc** [comment]
This is fixed in v3.X.X
