### ISSUE TITLE
Issue with multiple network Interfaces

### ISSUE THREAD

**Issue by CBK482** [juliuscc/heos-api#2]
Dear,
thanks for the wrapper. It will come very handy.
I struggled a bit to get the discovery working. I found out node-ssdp can have some issue with multiple NIC's. (VirtualBox on my laptop creates a virtual NIC)

Would you consider adding support for the "explicitSocketBind: Boolean" option?

Ciao,

Bert

"explicitSocketBind Boolean Bind sockets to each discovered interface explicitly instead of relying on the system. Might help with issues with multiple NICs."

**Comment by juliuscc** [comment]
Yes that is really something that I should fix. Connecting as it is now is really not perfect, and I would like to add TypeScript type definitions. I'll look into it in the weekend. Could you clarify what you mean with explicitSocketBind? I have a couple of ideas but maybe you could give som insight into what would work best for you

**Comment by EricByers** [comment]
Any chance you’d be open to converting to typescript for the code itself (can auto generate definitions then). I’d be interested in helping with that.

**Comment by juliuscc** [comment]
Now I've enabled users to create a connection without using the discovery function. The discovery function is far from perfect but now the package should be pretty good to use.

See commit https://github.com/juliuscc/heos-api/commit/dfba1318971b8c928d5b17cf39d0e10694bab5f9 for details if you want.

As this was a breaking change I've also upgraded the major version of the package.
