### ISSUE TITLE
Discover fails with 'Error [ERR_SOCKET_CANNOT_SEND]: Unable to send data'

### ISSUE THREAD

**Issue by maszaa** [juliuscc/heos-api#20]
I'm trying to discover my HEOS device on Windows 10 Pro with node.js 10.16.0 and heos-api 3.7.7. Due to using Hyper-V with Docker my OS has multiple (virtual) network interfaces. All discover functions throw the following error:

```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error [ERR_SOCKET_CANNOT_SEND]: Unable to send data
    at Socket.onListenError (dgram.js:328:22)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at state.handle.lookup (dgram.js:243:14)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Emitted 'error' event at:
    at Socket.onListenError (dgram.js:328:8)
    at Object.onceWrapper (events.js:286:20)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by maszaa** [comment]
I disabled all network interfaces except the hardware one but the problem remains.

**Comment by juliuscc** [comment]
Wierd. There is a known issue that you can't have Spotify on when doing a discover. Can you show the code that you run that create this issue?

**Comment by maszaa** [comment]
I got it work as a standalone.  But what I'm attempting to do is to have an Express API which acts as a proxy between a web app (SPA) and the HEOS device (Actually heos-api -> HEOS device). But when the Express app is started via `listen` function heos-api (dgram) can't send messages to the socket.

It seems it's not possible to run the heos-api in the browser due to dgram.

**Comment by maszaa** [comment]
Actually found the root cause. If I have any software running that uses UPnP heos-api (or dgram) can't send messages to the socket. Don't know if this is only Windows specific.

...but this is little problematic as I use my PC a UPnP server...

**Comment by juliuscc** [comment]
This is a problem as SSDP that is the basis of UPnP is specified on a specific UDP port and host. If any program on your computer already uses port 1900, heos-api can not open a new UDP socket on that port, and can therefore not use UPnP to discover HEOS devices.

I am looking in to if it is possible to use a different destination port than source port. If that is the case, maybe heos-api could open a UDP socket on a free port, and then send the message on port 1900. I am not sure if this is possible though.

**Comment by maszaa** [comment]
Tried it, works. At least port 1901 on my PC.

Maybe the UDP port could be defined via environment variable? If not set fallback to 1900.

**Comment by juliuscc** [comment]
Great! I will try to look into it and write a fix as soon as possible but it will probably take about a week.

**Comment by juliuscc** [comment]
Is it fixed for you?
