### ISSUE TITLE
Detect connection loss

### ISSUE THREAD

**Issue by xolom** [juliuscc/heos-api#23]
Hi.

I would like to detect connection losses, when i register event handlers.
Sometimes, the events are not triggered anymore and i think this comes from connection interrupts...

**Comment by juliuscc** [comment]
This sounds like a good idea. This is a bit related to #18.

In the background a HeosConnection has a TCP-socket to the connected HEOS Device. I think we should expose more things from the underlying TCP-socket. What do you think about that?

**Comment by xolom** [comment]
Sounds good. My first thought was to handle this in the _connect.ts_ module. Unfortunately i'm not well experienced in TypeScript..

**Comment by juliuscc** [comment]
Instead of passing a write function to HeosConnection we could provide the whole socket. See [link](https://github.com/juliuscc/heos-api/blob/720c80b04e59193218882ca6d5a3473c85e78a21/src/connection/heosConnection.ts#L19).

Then the HeosConnection could expose a function called `close` that only does a `close` on the socket.

I do not really know what you mean with list of opened sockets. If you connect you only open one socket. And the HeosConnection will have a referance to that socket.

**Comment by xolom** [comment]
> I do not really know what you mean with list of opened sockets. If you connect you only open one socket. And the HeosConnection will have a referance to that socket.

This would be for the disconnect functionality. 
Take this part of code for example:
```
heos_api.discoverAndConnect().then(connection =>
    connection
        .on({ commandGroup: 'event', command: 'player_now_playing_changed' }, (msg) => {
                // placeholder
        })
        .write('system', 'register_for_change_events', { enable: 'on' })
)
```

If the connection should be disconnected afterwards, one solution would be to store the socket connection in the lib itself as a list of connections. Calling a function like
`heos_api.disconnectAll()` 
could disconnect all open sockets.

A cleaner solution would be to have the whole socket object accessible outside the lib.

In any way i have the issue in my environment that the script where heos-api is used could be reloaded and 'reestablish' the connection. Therefore i would need to cleanup all existing connections, otherwise i have duplicated event listeners.

**Comment by juliuscc** [comment]
Sorry for not answering earlier. I have been working a lot. I agree with you that the best solution is to let the user be able to close a connection by providing a method for it.

The library is supposed to be quite lightweight, and if it would keep track of multiple connections I feel that the library would start providing functionality outside of it's scope.

In b74de7ad1ed301bd7275927d3d089481caf7534e I added support for closing a connection. I hope this solves your original issue. If not, I suggest you use `connection.onAll()` to try to print any event that you do not have a listener to.

**Comment by xolom** [comment]
I made a pull request for my proposal of detecting connection losses.

https://github.com/juliuscc/heos-api/compare/master...xolom:patch-1

**Comment by xolom** [comment]
Looks good. But for detecting an unexpected closed connection, i would propose a `connection.onClose()`  method where an event can be registered that is triggered by the socket (https://nodejs.org/api/net.html#net_event_close_1)

**Comment by juliuscc** [comment]
I’m sorry for not having time to fix this. If this is not done by next week, please remind me

**Comment by juliuscc** [comment]
Does 378fe04 fix this?

**Comment by xolom** [comment]
Awesome, thanks!
I will test this asap!

**Comment by maszaa** [comment]
I'm also in need for this functionality, great that you've found time to implement it! :+1: 

Unfortunately if I define `onClose` and `onError` for `HeosConnection` I can't write to the connection anymore. I think these are the reasons for that :)
https://github.com/juliuscc/heos-api/blob/378fe045edadfd18550186c97a1cafacc34257b4/src/connection/heosConnection.ts#L114
https://github.com/juliuscc/heos-api/blob/378fe045edadfd18550186c97a1cafacc34257b4/src/connection/heosConnection.ts#L124

**Comment by juliuscc** [comment]
Wow that definitely looks like a mistake

**Comment by juliuscc** [comment]
I made a commit where I removed those rows

**Comment by maszaa** [comment]
Seems to be working now, thanks! :+1:
