### ISSUE TITLE
Example fails

### ISSUE THREAD

**Issue by tommykjensen** [juliuscc/heos-api#28]
I am trying to run the example code but it fails with following errors:

`(node:14392) UnhandledPromiseRejectionWarning: No devices found
(node:14392) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14392) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Of course I have Heos players on my network.

**Comment by juliuscc** [comment]
Hi!

On line 5 there is a reference to a function called `saveToLog`, which doesn't exist. I assume you changed that. Did you add anything else or what did you change it to? Could you try the following example:

```js
const heos = require('heos-api')

heos.discoverAndConnect().then(connection =>
    connection.onAll(console.log)
)
```

**Comment by juliuscc** [comment]
Or even better, could you try the following:

```js
const heos = require('heos-api')

heos.discoverAndConnect().then(console.log)
```

**Comment by juliuscc** [comment]
You could also try the following just to see if any devices could be found:

```js
const heos = require('heos-api')

heos.discoverDevices({ timeout: 3000 }, console.log, () => console.log('Finished'))
```

**Comment by tommykjensen** [comment]
Thank you for responding.
The two first fail with the same error.
The last just displays "Finished" nothing else.

**Comment by tommykjensen** [comment]
As you can see from this output when I telnet directly to one of my speakers the api should be able to find my players. 

`heos://player/get_players
{"heos": {"command": "player/get_players", "result": "success", "message": ""}, "payload": [{"name": "Denon AVR-X4500H", "pid": 1682434575, "model": "Denon AVR-X4500H", "version": "1.520.200", "ip": "192.168.0.18", "network": "wired", "lineout": 0, "serial": "BCE27180701398"}, {"name": "HEOS 5L", "pid": 2081998824, "gid": 2081998824, "model": "HEOS 5", "version": "1.520.200", "ip": "192.168.0.15", "network": "wifi", "lineout": 0, "serial": "ACSG9181013823"}, {"name": "HEOS 5", "pid": -1600419679, "gid": 2081998824, "model": "HEOS 5", "version": "1.520.200", "ip": "192.168.0.31", "network": "wifi", "lineout": 0, "serial": "ACSG9190515852"}]}
`


I am working on windows desktop application and is using the dreamnucleus api for that and this can find my players. All from same pc as I am trying above javascripts. But since I found this api I thought I would give it a try because I think it is easier to design a nice user interface in html/angular instead of c#/xaml.

**Comment by juliuscc** [comment]
Thanks for trying out the suggestions.

I am trying to see how dreamnucleus/Heos does discovery differently to see if there is something that I am missing. As this project works for me and for others it is a bit difficult to figure out what is wrong.

Can you at least connect to a known IP? Like this:

```js
const heos = require('heos-api')
heos.connect('192.168.0.15').then(console.log)
```

or


```js
const heos = require('heos-api')
heos.connect('192.168.0.15').then(connection =>
    connection
        .onAll(console.log)
        .write('system', 'prettify_json_response', { enable: 'on' })
        .write('system', 'heart_beat')
)
```

**Note:** Switch 192.168.0.15 to a correct IP address.

**Comment by juliuscc** [comment]
Could you point me in the correct direction. How do you do a search with dreamnucleus/Heos. I can not find that in the documentation.

**Comment by tommykjensen** [comment]
I will try your suggestion when I am home later. Actually the search for the IP adresses when using dream nucleus I wrote in C# and provide a list of IP's to dreamnucleus to connect to, sorry for not being clear about that. I can send you the code later if you would like to have a look at that. I think it is this nuget package I use to scan the network https://github.com/Yortw/RSSDP

**Comment by juliuscc** [comment]
If you could share your implementation of how you use RSSDP, it would be great!

If you want to try something [node-ssdp](https://www.npmjs.com/package/node-ssdp) is a popular ssdp implementation that might work for you. You can use it to find one device and then connect to it.

Another detail is that you always only need to connect to one Heos device, even if you have many. You can send any command to any device **through** any other device. That is why heos-api is built for using only one session at a time.

**Comment by tommykjensen** [comment]
This is how I discover the players in C#

`public async Task SearchForDevices()
{
    using(var deviceLocator = new SsdpDeviceLocator(new SsdpCommunicationsServer(new SocketFactory(GetLocalIpAddress()), 19000)))
    {
        var foundDevices = await deviceLocator.SearchAsync("urn:schemas-denon-com:device:ACT-Denon:1");
        List < string > allDevices = new List<string>();
        foreach(var foundDevice in foundDevices)
        {
            if (foundDevice.DescriptionLocation.ToString().IndexOf("http") > -1) {
                try {
                    fullDevice = await foundDevice.GetDeviceInfo();
                }
                catch (Exception ex)
                {
                    Debug.WriteLine(ex);
                }
                if (fullDevice.FriendlyName.ToLower().IndexOf("heos") > -1) {
                    allDevices.Add(foundDevice.DescriptionLocation.Host.ToString());
                }
            }
        }
        heosIPs = allDevices.ToList().Distinct().ToList();
        Connect();
    }
}`

**Comment by tommykjensen** [comment]
And direct connect with ipaddress does work. So I might use this api and build my solution as a nodejs/angular app instead of a windows app.

**Comment by juliuscc** [comment]
Great! If you choose to use node-ssdp together with heos-api, please comment on how you did so that I can see a working piece of code compared to mine.

P.S. One \` will be an inline code. Three \`\`\` becomes a code block. You can also specify language for syntax highlighting.

[Look here for examples](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting)
