### ISSUE TITLE
Newbie

### ISSUE THREAD

**Issue by SPTimmer** [juliuscc/heos-api#29]
I'm sorry to add this as an issue but I'm very new to GitHub and coding and stuff.

That being said, I'm really interested in this API and would love to learn how to use it, because right now it makes no sense to me. I've installed node.js and git cloned this, but now I don't really know what to do. Can I use this API on the localhost server I have set up for example? Please help :/

Sincerely,
Sander

**Comment by juliuscc** [comment]
Hi!

Are you familiar with NPM (Node Package Manager)? NPM is included when you install Node, and is a manager for installing packages that others have created. Heos-api is uploaded to NPM, so the easiest way to use heos-api is to install it using npm.

## Prerequisite before installing a package with npm

First, you need to have a node-project. It sounds like you already have a project as you have set up a server. If you are not sure if you have a project or not, there is an easy way to check. Do you have a file called `package.json` in your directory? If yes, your directory is a node project.

`package.json` keeps track of what packages your project needs to work. This is called `dependencies`.

If you don't have a `package.json` in your directory, it is easy to add. You run `npm init -y` in the terminal. Make sure that you are in the correct directory when you do this.

## Installing a package with npm

Make sure your terminal is in the directory that has a `package.json` file. Then run
```
npm install <package-name>
```
where `<package-name>` is the package you want to install. In this case it is heos-api, so you would run
```
npm install heos-api
```

You can find more packages to download at https://www.npmjs.com/

After running the install command, you will have a directory called `node_modules` in your project. This contains installed dependencies, and you can ignore this. Just don't delete it.

## How to use installed packages

You can use your dependencies in any file in your project. The way you use them is to run `require`. It looks like this:
```javascript
const heos = require('heos-api')
```

After this you can start by trying out the example:

```javascript
const heos = require('heos-api')

heos.discoverAndConnect().then(connection =>
    connection
        .onAll(console.log)
        .on(
            {
                commandGroup: 'event',
                command: 'player_volume_changed'
            },
            console.info
        )
        .write('system', 'prettify_json_response', { enable: 'on' })
        .write('system', 'heart_beat')
        .write('player', 'set_volume', { pid: 1, level: 20 })
)
```

I hope this helps you get started. If there is anything specific with the package that is unclear, feel free to ask 🙂

**Comment by SPTimmer** [comment]
It really helped!! Thanks a lot,

**Question about the API in general**
Can I set the volume by using a PHP curl session/typing a link in the address bar in my browser?

**Trouble codewise**
Also, I tried the example script but it didn't work. I used npm start in Git Bash but somehow the set_volume command failed, any clue why that may be? The output is in the image below.

![image](https://user-images.githubusercontent.com/62361771/77194431-43be8780-6ae0-11ea-8c61-f472de52f17f.png)

Anyway, thanks a lot for your quick response! I really was on the verge of giving up.
Sincerely,
Sander

Edit: found the answer to one question I had, I overlooked it in your description

**Comment by juliuscc** [comment]
## Answer to the first question:
I am not 100% sure what you mean but I think you are trying to create a web server, that you can send requests to, which will result in commands sent to your HEOS device. Like this:

![Copy of web-proxy](https://user-images.githubusercontent.com/8337202/77224494-862aa780-6b66-11ea-9e07-65bef5c329f9.jpg)

This library only provides an easy way to do 3 and 4. The part where you receive requests is up to you. I can provide tips on how to do that, but I think that maybe you are solving a problem that is overly complicated. **What is the actual solution that you are trying to create?** There might be a much simpler way to do this.

## Answer to the second question
That was an interesting error. It seems as if your device does not allow the volume to be changed. Do you have multiple HEOS devices on your network, and what devices are they?

Also can you run the following and send he result:

```javascript

const heos = require('heos-api')
heos.discoverDevices(3000, console.log)
```

**Comment by wammesjeroen** [comment]
Hey There!

thanks for this cool package! I was trying to use this at home and I succeeded to communicate with my HEOS devices. Now I want make a small Angular app and use node express to create APIs to control my devices. But I don't know how pass the response message (for example "now playing" back to the front end, via the API. You can log the responses from the HEOS device (callback function in "onAll" or "on" function), but you have to wait for the promises to be resolved:

app.get('/heos', function (req, res) {
  test()
    .then(function (data) {
      res.send(data)
    })
    .catch(function (e) {
      res.status(500, {
        error: e
      });
    })
});

function test() {
  const heos = require('heos-api')

  return heos.discoverAndConnect().then(connection =>
    connection
      .onAll(collectData) //do something to collect return messages
      .write('system', 'prettify_json_response', { enable: 'on' })
      .write('system', 'heart_beat')
      .write('player', 'get_now_playing_media', { pid: 1 })
  )
}

Maybe you can help me a little bit?

thanks!
